# try -s 
synth:
	espeak -w silva3.wav -v pt -f silva3.txt
	espeak -w carta.wav -v pt -f carta.txt

synth-pag7:
	espeak -w silva_pag7_.wav -v pt -f silva_pag7_.txt

synth-pag6:
	espeak -w pag6.wav -v pt-br -p 20 -s 30 -f pag6.txt
